image:
  file: Dockerfile
  
ports:
  - port: 8001
  
tasks:
  -  command: mkdir /workspace/entangled/logs                                                                    &&
              mkdir /workspace/entangled/possible-dependencies                                                   &&
              touch /workspace/entangled/logs/gitpod-install-log.txt                                             &&
       

              echo "Starting .gitpod.yml installation" &>>  /workspace/entangled/logs/gitpod-install-log.txt     &&
              
              cd /workspace/entangled/possible-dependencies                                                      &&
              
              git clone https://github.com/whoshuu/cpr.git                                                       &&
              git clone https://github.com/curl/curl.git                                                         &&
              git clone https://github.com/google/googletest.git                                                 &&
              git clone https://github.com/nlohmann/json.git                                                     &&
              git clone https://github.com/XKCP/XKCP.git                                                         &&
              
              cd ..                                                                                              &&
              doxygen ./Doxyfile                                                                                 &&
              mv public publicOld                                                                                &&
              mv out/html public                                                                                 &&
              
              echo "Starting Apache"                   &>>  /workspace/entangled/logs/gitpod-install-log.txt     &&   
              apachectl start                                                                                    &&
              gp preview $(gp url 8001)                                                                          &&
              
              
              echo "Ending .gitpod.yml installation"  &>>   /workspace/entangled/logs/gitpod-install-log.txt    
              
              
     
